"use client"

import { useMemo, useState } from "react"
import { ArrowRight, ShoppingBasket, Check, ChevronDown, Clock3, MapPin, Menu, Search, SlidersHorizontal, X } from "lucide-react"
import { developmentComparison } from "@/data/dev-fixtures"
import { effectivePrice } from "@/lib/compare"
import type { Offer } from "@/types/quickcompare"

const popular = ["Milk", "Eggs", "Bread", "Tomatoes", "Cauliflower"]

function money(value?: number) { return value === undefined ? "—" : `₹${value}` }
function PlatformMark({ offer }: { offer: Offer }) { return <span className="platform-mark" style={{ background: offer.platform.color }}>{offer.platform.shortName}</span> }

function LocationDialog({ onClose }: { onClose: () => void }) { return <div className="dialog-backdrop" role="presentation" onClick={onClose}><div className="dialog" role="dialog" aria-modal="true" aria-labelledby="location-title" onClick={(event) => event.stopPropagation()}><div className="dialog-head"><div><p className="eyebrow">Delivery location</p><h2 id="location-title">Where should we compare?</h2></div><button className="icon-button" aria-label="Close location dialog" onClick={onClose}><X size={18}/></button></div><div className="location-current"><MapPin size={18}/><div><strong>Pune</strong><span>Prices and availability will be checked for this city.</span></div><Check size={18} className="check"/></div><label className="field-label" htmlFor="pincode">Pincode (optional)</label><input id="pincode" className="text-input" placeholder="Enter a 6-digit pincode" inputMode="numeric"/><button className="primary-button dialog-action" onClick={onClose}>Use Pune location</button></div></div> }

function Header({ onLocation }: { onLocation: () => void }) { return <header className="site-header"><div className="header-inner"><a className="wordmark" href="#top" aria-label="QuickCompare home"><span>Quick</span>Compare</a><nav className="desktop-nav" aria-label="Primary navigation"><a href="#compare">Compare</a><a href="#how-it-works">How it works</a></nav><div className="header-actions"><button className="location-button" onClick={onLocation}><MapPin size={16}/><span>Pune</span><ChevronDown size={14}/></button><a className="basket-button" href="#basket" aria-label="Open basket"><ShoppingBasket size={19}/><span>Basket</span></a><button className="menu-button" aria-label="Open menu"><Menu size={21}/></button></div></div></header> }

function SearchHero({ query, setQuery, onSearch }: { query: string; setQuery: (value: string) => void; onSearch: () => void }) { return <section className="hero" id="top"><div className="hero-copy"><div className="section-kicker"><span className="kicker-dot"/>Live comparison, made simple</div><h1>Compare before<br/><em>you buy.</em></h1><p>Find the best available price across quick-commerce platforms, for your location.</p></div><div className="search-wrap"><Search size={20}/><label className="sr-only" htmlFor="product-search">Search for products</label><input id="product-search" value={query} onChange={(event) => setQuery(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && !event.nativeEvent.isComposing && event.keyCode !== 229) onSearch() }} placeholder="Search for groceries, household essentials..."/><button className={query ? "clear-search" : "search-submit"} onClick={query ? () => setQuery("") : onSearch} aria-label={query ? "Clear search" : "Search"}>{query ? <X size={18}/> : <ArrowRight size={19}/>}</button></div><div className="popular"><span>Popular searches</span>{popular.map((item) => <button key={item} onClick={() => { setQuery(item); if (item === "Cauliflower") onSearch() }}>{item}</button>)}</div></section> }

function BestPrice({ offer }: { offer: Offer }) { const total = effectivePrice(offer.price, offer.fees); return <div className="best-price"><div className="best-label"><span className="best-icon"><Check size={16}/></span><span>Best available price</span></div><div className="best-body"><div><p className="offer-platform"><PlatformMark offer={offer}/>{offer.platform.name}</p><h3>{money(total)} <small>effective cost</small></h3><p className="best-note">{money(offer.price)} product price <span>+</span> {money(offer.fees.handling)} handling</p></div><div className="best-right"><span className="availability"><i/>Available</span><span>{offer.deliveryEstimate}</span></div></div></div> }

function OfferCard({ offer, best }: { offer: Offer; best?: boolean }) { const total = effectivePrice(offer.price, offer.fees); const unavailable = offer.availability !== "available"; return <article className={`offer-card ${best ? "is-best" : ""} ${unavailable ? "is-unknown" : ""}`}><div className="offer-top"><div className="offer-platform"><PlatformMark offer={offer}/><strong>{offer.platform.name}</strong></div>{best && <span className="best-pill">Best price</span>}</div><div className="variant">{offer.product.name} <b>·</b> {offer.variant.label}</div><div className="price-row"><div><strong>{money(offer.price)}</strong>{offer.mrp && <del>{money(offer.mrp)}</del>}</div>{offer.discount && <span className="discount">{offer.discount}% off</span>}</div><div className="detail-row"><span>Effective cost</span><strong>{money(total)}</strong></div><div className="offer-footer">{unavailable ? <span className="unavailable"><i/>Temporarily unavailable</span> : <span className="delivery"><Clock3 size={14}/>{offer.deliveryEstimate}</span>}<button className="view-offer" disabled={unavailable}>View offer <ArrowRight size={15}/></button></div></article> }

function Results({ onSearch }: { onSearch: () => void }) { const data = developmentComparison; const [selectedVariant, setSelectedVariant] = useState(data.product.variants[0].id); const offers = useMemo(() => data.offers.filter((offer) => offer.variant.id === selectedVariant), [selectedVariant]); const best = offers.filter((offer) => offer.availability === "available").sort((a,b) => (effectivePrice(a.price,a.fees) ?? Infinity) - (effectivePrice(b.price,b.fees) ?? Infinity))[0]; return <section className="results" id="compare"><div className="results-head"><div><div className="eyebrow-line"><span>Comparison results</span><span className="fixture-tag">Development fixture</span></div><h2>{data.product.name}</h2><p className="result-meta"><MapPin size={15}/> Pune <span>·</span> checked just now <span>·</span> {data.platformsCompared} platforms</p></div><button className="filter-button"><SlidersHorizontal size={16}/> Filters</button></div><div className="partial-note"><span><span className="partial-icon">i</span><strong>{data.platformsResponded} of {data.platformsCompared} platforms responded</strong></span><span>One platform is temporarily unavailable</span></div><div className="variant-bar"><span>Compare variant</span><div className="variant-options">{data.product.variants.map((variant) => <button key={variant.id} className={variant.id === selectedVariant ? "selected" : ""} onClick={() => setSelectedVariant(variant.id)}>{variant.quantity}<small>{variant.label}</small></button>)}</div></div>{best && <BestPrice offer={best}/>}<div className="offers-heading"><h3>All offers <span>{offers.length}</span></h3><button className="history-link">Price history <ArrowRight size={15}/></button></div><div className="offers-grid">{offers.map((offer) => <OfferCard key={offer.id} offer={offer} best={best?.id === offer.id}/>)}</div><div className="results-foot"><span><Clock3 size={14}/> Observation time: {data.observedAt}</span><button onClick={onSearch}>Search another product <ArrowRight size={15}/></button></div></section> }

export default function CompareApp() { const [query, setQuery] = useState("Cauliflower"); const [showResults, setShowResults] = useState(true); const [locationOpen, setLocationOpen] = useState(false); const search = () => setShowResults(query.trim().length > 0); return <><Header onLocation={() => setLocationOpen(true)}/><main><SearchHero query={query} setQuery={setQuery} onSearch={search}/>{showResults ? <Results onSearch={() => { setQuery(""); setShowResults(false) }}/> : <div className="empty-search"><Search size={24}/><h2>Start with a product</h2><p>Search for an everyday essential to compare prices near Pune.</p></div>}</main><footer><span>QuickCompare</span><span>Prices vary by location and time. Always verify at checkout.</span></footer>{locationOpen && <LocationDialog onClose={() => setLocationOpen(false)}/>}</> }
