"use client"

import { useMemo, useState } from "react"
import { ArrowRight, Check, ChevronDown, Clock3, MapPin, Menu, Search, SlidersHorizontal, X } from "lucide-react"
import { developmentComparison } from "@/data/dev-fixtures"
import { effectivePrice, formatFreshness, getPriceBreakdown, getUnitPrice } from "@/lib/compare"
import type { Availability, Offer, ProductVariant } from "@/types/quickcompare"

const popular = ["Milk", "Eggs", "Bread", "Tomatoes", "Cauliflower"]
const money = (value?: number) => value === undefined ? "—" : `₹${value}`

function PlatformMark({ offer }: { offer: Offer }) { return <span className="platform-mark" style={{ background: offer.platform.color }}>{offer.platform.shortName}</span> }
function AvailabilityBadge({ status }: { status: Availability }) { const labels: Record<Availability, string> = { available: "Available", out_of_stock: "Out of stock", unavailable: "Platform unavailable", data_unavailable: "Data unavailable", stale: "Stale data" }; return <span className={`availability ${status}`}><i />{labels[status]}</span> }
function FreshnessIndicator({ observedAt }: { observedAt?: string }) { return <span className="freshness"><Clock3 size={13} />{formatFreshness(observedAt)}</span> }

function LocationDialog({ onClose }: { onClose: () => void }) { return <div className="dialog-backdrop" role="presentation" onClick={onClose}><div className="dialog" role="dialog" aria-modal="true" aria-labelledby="location-title" onClick={(event) => event.stopPropagation()}><div className="dialog-head"><div><p className="eyebrow">Delivery location</p><h2 id="location-title">Where should we compare?</h2></div><button className="icon-button" aria-label="Close location dialog" onClick={onClose}><X size={18} /></button></div><div className="location-current"><MapPin size={18} /><div><strong>Pune</strong><span>Prices and availability depend on this location.</span></div><Check size={18} className="check" /></div><label className="field-label" htmlFor="pincode">Pincode (optional)</label><input id="pincode" className="text-input" placeholder="Enter a 6-digit pincode" inputMode="numeric" /><button className="primary-button dialog-action" onClick={onClose}>Use Pune location</button></div></div> }
function Header({ onLocation }: { onLocation: () => void }) { return <header className="site-header"><div className="header-inner"><a className="wordmark" href="#top" aria-label="QuickCompare home"><span>Quick</span>Compare</a><nav className="desktop-nav" aria-label="Primary navigation"><a href="#compare">Compare</a><a href="#how-it-works">How it works</a></nav><div className="header-actions"><button className="location-button" onClick={onLocation}><MapPin size={16} /><span>Pune</span><ChevronDown size={14} /></button><a className="basket-button" href="#basket">Basket</a><button className="menu-button" aria-label="Open menu"><Menu size={21} /></button></div></div></header> }
function SearchBar({ query, setQuery, onSearch }: { query: string; setQuery: (value: string) => void; onSearch: () => void }) { return <div className="search-wrap"><Search size={20} /><label className="sr-only" htmlFor="product-search">Search for products</label><input id="product-search" value={query} onChange={(event) => setQuery(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && !event.nativeEvent.isComposing && event.keyCode !== 229) onSearch() }} placeholder="Search for groceries, household essentials..." /><button className={query ? "clear-search" : "search-submit"} onClick={query ? () => setQuery("") : onSearch} aria-label={query ? "Clear search" : "Search"}>{query ? <X size={18} /> : <ArrowRight size={19} />}</button></div> }
function SearchHero({ query, setQuery, onSearch }: { query: string; setQuery: (value: string) => void; onSearch: () => void }) { return <section className="hero" id="top"><div className="hero-copy"><div className="section-kicker"><span className="kicker-dot" />Live comparison, made simple</div><h1>Compare before<br /><em>you buy.</em></h1><p>Find the best available price across quick-commerce platforms, for your location.</p></div><SearchBar query={query} setQuery={setQuery} onSearch={onSearch} /><div className="popular"><span>Popular searches</span>{popular.map((item) => <button key={item} onClick={() => { setQuery(item); if (item === "Cauliflower") onSearch() }}>{item}</button>)}</div></section> }
function VariantSelector({ variants, selected, onChange }: { variants: ProductVariant[]; selected: string; onChange: (id: string) => void }) { return <div className="variant-bar"><span>Compare variant</span><div className="variant-options">{variants.map((variant) => <button key={variant.id} className={variant.id === selected ? "selected" : ""} onClick={() => onChange(variant.id)} aria-pressed={variant.id === selected}>{variant.name}</button>)}</div></div> }
function PriceBreakdown({ offer }: { offer: Offer }) { const breakdown = getPriceBreakdown(offer); return <div className="breakdown"><div><span>Product price</span><strong>{money(breakdown.productPrice)}</strong></div><div><span>Delivery fee</span><strong>{money(breakdown.deliveryFee)}</strong></div><div><span>Handling/platform fee</span><strong>{money(breakdown.handlingFee)}</strong></div><div><span>Discount</span><strong>{breakdown.discount ? `−${money(breakdown.discount)}` : "—"}</strong></div><div className="breakdown-total"><span>Effective cost</span><strong>{money(breakdown.effectiveCost)}</strong></div></div> }
function BestPriceCard({ offer }: { offer: Offer }) { return <div className="best-price"><div className="best-label"><span className="best-icon"><Check size={16} /></span><span>Best price for selected quantity</span></div><div className="best-body"><div><p className="offer-platform"><PlatformMark offer={offer} />{offer.platform.name}</p><h3>{money(effectivePrice(offer))} <small>effective cost</small></h3><p className="best-note">Save compared with the next-best comparable offer</p></div><div className="best-right"><AvailabilityBadge status={offer.availability} /><span>{offer.deliveryEstimate}</span></div></div></div> }
function OfferCard({ offer, best }: { offer: Offer; best?: boolean }) { const [expanded, setExpanded] = useState(false); const unitPrice = getUnitPrice(offer); const unavailable = offer.availability !== "available"; return <article className={`offer-card ${best ? "is-best" : ""} ${unavailable ? "is-unknown" : ""}`}><div className="offer-top"><div className="offer-platform"><PlatformMark offer={offer} /><strong>{offer.platform.name}</strong></div>{best && <span className="best-pill">Best price</span>}</div><div className="variant">{offer.productName} <b>·</b> {offer.variant.name}</div><div className="price-row"><div><strong>{money(offer.price)}</strong>{offer.mrp !== undefined && <del>{money(offer.mrp)}</del>}</div>{offer.discount !== undefined && <span className="discount">Save ₹{offer.discount}</span>}</div>{unitPrice && <div className="unit-price">{unitPrice.label}</div>}<div className="detail-row"><span>Effective cost</span><strong>{money(effectivePrice(offer))}</strong></div><div className="offer-meta"><AvailabilityBadge status={offer.availability} />{offer.deliveryEstimate && <span>{offer.deliveryEstimate}</span>}<FreshnessIndicator observedAt={offer.observedAt} /></div><div className="offer-footer"><button className="breakdown-toggle" onClick={() => setExpanded(!expanded)} aria-expanded={expanded}>{expanded ? "Hide price breakdown" : "Price breakdown"}<ChevronDown size={15} className={expanded ? "rotate" : ""} /></button><a className={`view-offer ${unavailable ? "disabled" : ""}`} href={unavailable ? undefined : offer.productUrl}>View offer <ArrowRight size={15} /></a></div>{expanded && <PriceBreakdown offer={offer} />}</article> }
function ComparisonFilters({ availableOnly, setAvailableOnly }: { availableOnly: boolean; setAvailableOnly: (value: boolean) => void }) { return <div className="filter-row"><label><input type="checkbox" checked={availableOnly} onChange={(event) => setAvailableOnly(event.target.checked)} /> Available only</label><label>Sort by <select defaultValue="best"><option value="best">Best price</option><option value="fastest">Fastest delivery</option><option value="value">Best value</option></select></label></div> }
function Results({ onSearch }: { onSearch: () => void }) { const data = developmentComparison; const [selectedVariant, setSelectedVariant] = useState(data.product.variants[0].id); const [availableOnly, setAvailableOnly] = useState(false); const [filtersOpen, setFiltersOpen] = useState(false); const offers = useMemo(() => data.offers.filter((offer) => offer.variant.id === selectedVariant && (!availableOnly || offer.availability === "available")), [selectedVariant, availableOnly]); const best = offers.filter((offer) => offer.availability === "available").sort((a, b) => effectivePrice(a) - effectivePrice(b))[0]; return <section className="results" id="compare"><div className="results-head"><div><div className="eyebrow-line"><span>Comparison results</span><span className="fixture-tag">Development fixture</span></div><h2>{data.product.name}</h2><p className="result-meta"><MapPin size={15} /> {data.location.city} <span>·</span> Prices and availability depend on location</p><p className="result-freshness"><Check size={14} /> Checked recently · {data.platformsResponded} of {data.platformsCompared} platforms responded</p></div><button className="filter-button" onClick={() => setFiltersOpen(!filtersOpen)} aria-expanded={filtersOpen}><SlidersHorizontal size={16} /> Filters</button></div>{filtersOpen && <ComparisonFilters availableOnly={availableOnly} setAvailableOnly={setAvailableOnly} />}<div className="partial-note"><span><span className="partial-icon">i</span><strong>{data.platformsResponded} of {data.platformsCompared} platforms responded</strong></span><span>Blinkit is temporarily unavailable</span></div><VariantSelector variants={data.product.variants} selected={selectedVariant} onChange={setSelectedVariant} />{best && <BestPriceCard offer={best} />}<div className="offers-heading"><h3>All offers <span>{offers.length}</span></h3><button className="history-link" disabled>Price history <ArrowRight size={15} /></button></div><div className="offers-grid">{offers.map((offer) => <OfferCard key={offer.id} offer={offer} best={best?.id === offer.id} />)}</div>{offers.length === 0 && <div className="empty-results"><h3>No comparable offers found</h3><p>We couldn&apos;t find comparable offers for this product and location.</p><button className="primary-button" onClick={onSearch}>Try another product</button></div>}<div className="results-foot"><span><Clock3 size={14} /> Observations are development data, not live prices.</span><button onClick={onSearch}>Search another product <ArrowRight size={15} /></button></div></section> }
export default function CompareApp() { const [query, setQuery] = useState("Cauliflower"); const [showResults, setShowResults] = useState(true); const [locationOpen, setLocationOpen] = useState(false); const search = () => setShowResults(query.trim().length > 0); return <><Header onLocation={() => setLocationOpen(true)} /><main><SearchHero query={query} setQuery={setQuery} onSearch={search} />{showResults ? <Results onSearch={() => { setQuery(""); setShowResults(false) }} /> : <div className="empty-search"><Search size={24} /><h2>Start with a product</h2><p>Search for an everyday essential to compare prices near Pune.</p></div>}</main><footer><span>QuickCompare</span><span>Prices vary by location and time. Always verify at checkout.</span></footer>{locationOpen && <LocationDialog onClose={() => setLocationOpen(false)} />}</> }
